# Generated by Django 5.0.8 on 2024-08-17 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=46)),
                ('transactionID', models.CharField(max_length=46)),
                ('type', models.CharField(max_length=46)),
                ('description', models.CharField(max_length=46)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspend')], default='active', max_length=46)),
                ('transaction_date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.mdevice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.servicevendor')),
            ],
        ),
    ]
