# Generated by Django 5.0.8 on 2024-08-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetransactions',
            name='type',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspend')], default='active', max_length=46),
        ),
    ]
