# Generated by Django 5.0.8 on 2024-10-03 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='time',
            new_name='session_id',
        ),
    ]
