# Generated by Django 5.0.8 on 2024-10-03 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_rename_time_attendance_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='day',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='type',
        ),
    ]
