# Generated by Django 5.0.8 on 2024-10-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_rename_day_attendance_date_remove_attendance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='session_id',
            field=models.CharField(default='0000', max_length=46, unique=True),
        ),
    ]
