# Generated by Django 5.0.8 on 2024-10-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_attendance_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='session_id',
            field=models.CharField(max_length=46, unique=True),
        ),
    ]
