# Generated by Django 5.0.8 on 2024-10-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_attendance_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensetransactions',
            name='type',
        ),
        migrations.AddField(
            model_name='expensetransactions',
            name='sessionID',
            field=models.CharField(default='0000000', max_length=46, unique=True),
        ),
    ]
