# Generated by Django 5.0.8 on 2024-10-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_remove_expensetransactions_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransactions',
            name='sessionID',
            field=models.CharField(default='0000000', max_length=46),
        ),
    ]
