# Generated by Django 5.0.8 on 2024-10-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_alter_expensetransactions_sessionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='closed_amount',
            field=models.IntegerField(default=0, max_length=23),
        ),
        migrations.AddField(
            model_name='attendance',
            name='open_amount',
            field=models.IntegerField(default=0, max_length=23),
        ),
    ]
