# Generated by Django 5.0.8 on 2024-10-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_attendance_closed_amount_attendance_open_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('logged_in', 'Logged In'), ('logged_out', 'Logged Out'), ('suspended', 'Cancelled')], default='logged_in', max_length=46),
        ),
    ]
